// <auto-generated />
using System;
using CashTrackApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashTrackApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260330213215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CashTrackApi.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Nombre = "Alimentación"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Nombre = "Transporte"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Nombre = "Entretenimiento"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Nombre = "Servicios"
                        },
                        new
                        {
                            IdCategoria = 5,
                            Nombre = "Salud"
                        });
                });

            modelBuilder.Entity("CashTrackApi.Models.DetalleGasto", b =>
                {
                    b.Property<int>("IdDetalleGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleGasto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleGasto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("DetallesGasto");
                });

            modelBuilder.Entity("CashTrackApi.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("CashTrackApi.Models.Gasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGasto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDetalleGasto")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdGasto");

                    b.HasIndex("IdDetalleGasto");

                    b.HasIndex("IdEstado");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("CashTrackApi.Models.DetalleGasto", b =>
                {
                    b.HasOne("CashTrackApi.Models.Categoria", "Categoria")
                        .WithMany("DetallesGasto")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CashTrackApi.Models.Gasto", b =>
                {
                    b.HasOne("CashTrackApi.Models.DetalleGasto", "DetalleGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("IdDetalleGasto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashTrackApi.Models.Estado", "Estado")
                        .WithMany("Gastos")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleGasto");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("CashTrackApi.Models.Categoria", b =>
                {
                    b.Navigation("DetallesGasto");
                });

            modelBuilder.Entity("CashTrackApi.Models.DetalleGasto", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("CashTrackApi.Models.Estado", b =>
                {
                    b.Navigation("Gastos");
                });
#pragma warning restore 612, 618
        }
    }
}
